### ISSUE TITLE
求自定义icon功能

### ISSUE THREAD

**Issue by moke8** [hymnly133/Sapphire-EnhancedDesktop#12]
想把bat文件放在桌面上并美化，尝试过先创建快捷方式并修改icon，快捷方式拖到桌面上icon还是那个默认的

**Comment by hymnly133** [comment]
目前可以右键选择一个 软件/文件 的图标作为替代，之后会制作选择图片功能

**Comment by hymnly133** [comment]
已完善自定义Icon
