### ISSUE TITLE
希望能够支持Steam以外的游戏图标封面化

### ISSUE THREAD

**Issue by FENBIANKELI** [hymnly133/Sapphire-EnhancedDesktop#15]
我想在
https://www.steamgriddb.com/
里寻找封面给游戏图标进行配置，就像这样
![Snipaste_2024-07-22_01-32-21](https://github.com/user-attachments/assets/993d3648-8544-464f-ab65-782c1d6e1ea4)

**Comment by hymnly133** [comment]
已更新，请自选封面

**Comment by FENBIANKELI** [comment]
> 已更新，请自选封面

大佬太强~~~太棒啦~~~
要是能支持CSS就能棒了233，有CSS的话就能够进一步DIY了，还能够启用其他人的预设。

**Comment by hymnly133** [comment]
等找到qt能支持css的方法再考虑css，但是主题自定义与迁移功能是在开发计划中的
