### ISSUE TITLE
并不完全符合操作直觉

### ISSUE THREAD

**Issue by misaka10384** [hymnly133/Sapphire-EnhancedDesktop#16]
无法选中图标
无法对图标使用快捷键 比如F2重命名  或者ctrl+c/v、del
无法自动添加桌面新增的任何文件/夹
无法在桌面上快捷新建文件/夹
在应用桌面上删除后无法同步至系统桌面
......

**Comment by hymnly133** [comment]
除了新增文件夹，以上操作已经全部补齐

**Comment by misaka10384** [comment]
> 除了新增文件夹，以上操作已经全部补齐

好事

**Comment by hymnly133** [comment]
已经基本补全
