### ISSUE TITLE
标签出现时可以自动判断向左向右出现

### ISSUE THREAD

**Issue by AImixAE** [hymnly133/Sapphire-EnhancedDesktop#17]
在屏幕右边缘附近悬浮图标时，弹出的标签会一直在右侧出现，看不到后面的内容
![QQ_1721703473078](https://github.com/user-attachments/assets/fc260ad5-9a6f-4d79-9839-05decc7061be)
可以判断一下`如果标签右侧坐标超出屏幕大小，则向左侧显示`

**Comment by hymnly133** [comment]
更新完成，顺便加了一点点漂移

**Comment by Hwenray** [comment]
此问题在多屏环境下仍未解决
