### ISSUE TITLE
希望兼容来自explorer的文件拖拽/复制

### ISSUE THREAD

**Issue by Hwenray** [hymnly133/Sapphire-EnhancedDesktop#27]
希望兼容来自explorer的文件拖拽/复制
P.S.这是不是有点强人所难了XD

**Comment by hymnly133** [comment]
之前的版本已经有了，但是在请求管理员权限之后失效，会在下个发行版修复

**Comment by Hwenray** [comment]
有管理员权限就失效的原因是Windows不允许不同权限级的应用之间通信，可以参考在WPF下的解决方案（虽然未解决）
https://github.com/Hex-Dragon/PCL2/issues/2531#issuecomment-1822511620

**Comment by hymnly133** [comment]
已经尽量优化，但在当前qt版本下不适用，并在使用手册提供用户解决方案，希望有朝一日能完全解决
