### ISSUE TITLE
出现字体紊乱现象

### ISSUE THREAD

**Issue by Tz2H** [hymnly133/Sapphire-EnhancedDesktop#33]

**Comment by Tz2H** [comment]
<img width="317" alt="image" src="https://github.com/user-attachments/assets/d4b1f49a-66ce-4b1e-a961-aa0d1928dc7d">
lei's
类似如此情况

**Comment by Tz2H** [comment]
找到问题出在哪里了 和CAD的字体冲突了 但是不知道如何解决

**Comment by Tz2H** [comment]
可以通过高级设置中的字体更换解决 看起来像是win11的问题

**Comment by zhaochengchenggithub** [comment]
高级设置指的windows么

**Comment by Tz2H** [comment]
> 高级设置指的windows么

可以在win中的字体设置解决 也可以用此项目的高级设置解决 在说明文档中有写如何打开
