### ISSUE TITLE
鼠标移动到暗色图标上会直接全黑啥也看不到

### ISSUE THREAD

**Issue by wanqian-windrunner** [hymnly133/Sapphire-EnhancedDesktop#36]
如下图

![image](https://github.com/user-attachments/assets/686c5720-4095-4ddc-b543-5bf3a8e873b8)

**Comment by hymnly133** [comment]
可以将聚焦时的颜色比率调低一点

**Comment by wanqian-windrunner** [comment]
好的感谢
