### ISSUE TITLE
不兼容多显示器

### ISSUE THREAD

**Issue by xiaoshuaixia2012** [hymnly133/Sapphire-EnhancedDesktop#4]
在接入多个显示器时（我接了2个屏幕），会优先选择第2屏来显示，如果第2屏和第1屏的分辨率不同，可能还会出现第2屏也显示不全的情况。
如果不好做到每个显示器都单独显示，我建议先让软件的内容显示在第1屏。

**Comment by hymnly133** [comment]
多屏支持已更新
