### ISSUE TITLE
Shift右键无法打开任何右键菜单

### ISSUE THREAD

**Issue by tanstardream** [hymnly133/Sapphire-EnhancedDesktop#5]
在桌面同时点击右键和Shift时没有任何反应，没有任何反应，按住Shift时双击可以隐藏图标

**Comment by hymnly133** [comment]
目前只定向了对图标的shift右键功能，在空白处的右键功能没有好的实现，因为很多原生右键桌面菜单的功能已经用不上了（预计会加高级选项）
