### ISSUE TITLE
任何跨显示器操作导致崩溃

### ISSUE THREAD

**Issue by Wacchi-Lorie** [hymnly133/Sapphire-EnhancedDesktop#58]
将任何东西从一个显示器上拖到另一个显示器会导致崩溃
在本显示器创建并使用元素没有问题
[b363b31c-b5ea-4ed0-92b9-66192fd9d4aa.dmp](https://github.com/user-attachments/files/16767978/b363b31c-b5ea-4ed0-92b9-66192fd9d4aa.dmp)

**Comment by hymnly133** [comment]
将会在明天进行紧急修复

**Comment by hymnly133** [comment]
更新已发布
