### ISSUE TITLE
有关文字颜色的问题

### ISSUE THREAD

**Issue by Hwenray** [hymnly133/Sapphire-EnhancedDesktop#6]
请添加有关更改文字颜色的配置选项，and添加有关图标风格统一化的配置
![image](https://github.com/user-attachments/assets/21bbba01-b919-4fdd-958b-a363c32fc362)
否则风格将非常撕裂（如图
 and期待
#5
中提及的右键菜单有关实现的高级选项的实现

**Comment by hymnly133** [comment]
设计时考虑到了，有两种实现方案：

1.根据图标颜色是否深色进行调整，这样的话会出现有些黑字有些白字
2.全局Dark模式
3.自定义颜色混合比例：如0.5文件颜色+0.5自定义/系统主题色

感谢反馈

另外全局Style设置面板正在制作中
