### ISSUE TITLE
有关启动多个进程导致软件叠加显示的问题

### ISSUE THREAD

**Issue by Hwenray** [hymnly133/Sapphire-EnhancedDesktop#7]
建议加上进程判断，无聊时开了3，4个叠在一起😓

**Comment by Hwenray** [comment]
![image](https://github.com/user-attachments/assets/c0e8c2be-1dba-4c67-b6b9-e6dd69624a81)
😰

**Comment by hymnly133** [comment]
这我真没想到。。。下个版本修复
